import {
  pgTable,
  serial,
  bigint,
  integer,
  varchar,
  numeric,
  timestamp,
} from "drizzle-orm/pg-core";

export const apApartado = pgTable("ap_apartado", {
  id: serial("id").primaryKey(),
  ciclo: integer("ciclo"),
  servicioSuscritoDependiente: bigint("servicio_suscrito_dependiente", { mode: "number" }),
  servicioSuscritoPadre: bigint("servicio_suscrito_padre", { mode: "number" }),
  tipoServicio: integer("tipo_servicio"),
  descripcionServicio: varchar("descripcion_servicio", { length: 200 }),
  suscripcion: bigint("suscripcion", { mode: "number" }),
  fechaGeneracionFactura: varchar("fecha_generacion_factura", { length: 20 }),
  anoMesFactura: integer("ano_mes_factura"),
  nroFactura: bigint("nro_factura", { mode: "number" }),
  categoria: integer("categoria"),
  subCategoria: integer("sub_categoria"),
  valorImpuesto: numeric("valor_impuesto", { precision: 18, scale: 4 }),
  valorCartera: numeric("valor_cartera", { precision: 18, scale: 4 }),
  interesesMora: numeric("intereses_mora", { precision: 18, scale: 4 }),
  valorReconocimiento: numeric("valor_reconocimiento", { precision: 18, scale: 4 }),
  valorSeparacion: numeric("valor_separacion", { precision: 18, scale: 4 }),
  valorFinanciacion: numeric("valor_financiacion", { precision: 18, scale: 4 }),
  valorTotalFacturado: numeric("valor_total_facturado", { precision: 18, scale: 4 }),
  direccion: varchar("direccion", { length: 300 }),
  nroInstalacion: varchar("nro_instalacion", { length: 50 }),
  sujetoPasivoPdtoDependiente: varchar("sujeto_pasivo_pdto_dependiente", { length: 200 }),
  identificacionSujetoPasivo: varchar("identificacion_sujeto_pasivo", { length: 50 }),
  codDepartamento: integer("cod_departamento"),
  codMunicipio: integer("cod_municipio"),
  consumoEnergia: numeric("consumo_energia", { precision: 18, scale: 4 }),
});

export const apApartadoRecaudos = pgTable("ap_apartado_recaudos", {
  id: serial("id").primaryKey(),
  servicioSuscritoDependiente: bigint("servicio_suscrito_dependiente", { mode: "number" }),
  servicioSuscritoPadre: bigint("servicio_suscrito_padre", { mode: "number" }),
  tipoServicio: integer("tipo_servicio"),
  descripcionServicio: varchar("descripcion_servicio", { length: 200 }),
  suscripcion: bigint("suscripcion", { mode: "number" }),
  anoMesFactura: integer("ano_mes_factura"),
  nroFactura: bigint("nro_factura", { mode: "number" }),
  categoria: integer("categoria"),
  subCategoria: integer("sub_categoria"),
  valorRecaudoImpuesto: numeric("valor_recaudo_impuesto", { precision: 18, scale: 4 }),
  valorRecaudoIntereses: numeric("valor_recaudo_intereses", { precision: 18, scale: 4 }),
  valorRecaudoSeparacion: numeric("valor_recaudo_separacion", { precision: 18, scale: 4 }),
  valorReconocimiento: numeric("valor_reconocimiento", { precision: 18, scale: 4 }),
  valorOtrosRecaudos: numeric("valor_otros_recaudos", { precision: 18, scale: 4 }),
  valorTotalRecaudos: numeric("valor_total_recaudos", { precision: 18, scale: 4 }),
  fechaPago: varchar("fecha_pago", { length: 50 }),
  direccion: varchar("direccion", { length: 300 }),
  nroInstalacion: varchar("nro_instalacion", { length: 50 }),
  sujetoPasivoPdtoDependiente: varchar("sujeto_pasivo_pdto_dependiente", { length: 200 }),
  identificacionSujetoPasivo: varchar("identificacion_sujeto_pasivo", { length: 50 }),
  codDepartamento: integer("cod_departamento"),
  codMunicipio: integer("cod_municipio"),
  valorReconocimientoCovid: numeric("valor_reconocimiento_covid", { precision: 18, scale: 4 }),
});
